### ISSUE TITLE
Questions about the dataset

### ISSUE THREAD

**Issue by baidu2018** [ashuneema28/Deman-Prediction-for-EV#1]
Hello, I want to know the specific content of this data set, because I can't run the program, I can't find the data set, I don't understand the meaning of the Grouped_data_With_Prev_Value_Column file.  Thank you！

**Comment by ashuneema28** [comment]
Hello , i added the Main data file on which the pre processing is done.
 The Grouped_data_With_Prev_Value_Column file is the file created after some pre-processing is done on the dataset. What it does is : It groups the data according to 6 specific charging station based on their MAC address for the year 2019 and 2020 (because that data is the most accurate), then calculates the energy required at a given hour , and also adds a column for calculating the previous energy at that given hour. For example if at at hour 4 the energy is 6.78 KW/hr then at next instance of hour 4, the previous value column will contain value 6.78 KW/hr

**Comment by baidu2018** [comment]
thank you for your reply! I look at the program again
